package com.banry.pscm.tenant.persist.dao;

import java.util.List;

import com.banry.pscm.tenant.persist.mapper.BizAuthoritySQLBuilder;
import com.banry.pscm.tenant.service.biz.BizAuthority;
import com.banry.pscm.tenant.service.biz.BizAuthorityKey;

import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;

public interface BizAuthorityMapper {
	
	@SelectProvider(type = BizAuthoritySQLBuilder.class,method = "findBizAuthorityBySqlWhere")
	List<BizAuthority> findBizAuthListBySqlWhere(String sqlWhere);
	
	@InsertProvider(type = BizAuthoritySQLBuilder.class, method = "insertBizAuthority")
	int insertBizAuthority(@Param("list") List<BizAuthority> bizAuthorityList);
	
	@DeleteProvider(type = BizAuthoritySQLBuilder.class, method = "deleteBizAuthority")
	int deleteBizAuthority(@Param("list") List<BizAuthority> bizAuthorityList);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbiz
     *
     * @mbg.generated Sat Apr 07 15:50:56 CST 2018
     */
    int deleteByPrimaryKey(BizAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbiz
     *
     * @mbg.generated Sat Apr 07 15:50:56 CST 2018
     */
    int insert(BizAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbiz
     *
     * @mbg.generated Sat Apr 07 15:50:56 CST 2018
     */
    int insertSelective(BizAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbiz
     *
     * @mbg.generated Sat Apr 07 15:50:56 CST 2018
     */
    BizAuthority selectByPrimaryKey(BizAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbiz
     *
     * @mbg.generated Sat Apr 07 15:50:56 CST 2018
     */
    int updateByPrimaryKeySelective(BizAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenbiz
     *
     * @mbg.generated Sat Apr 07 15:50:56 CST 2018
     */
    int updateByPrimaryKey(BizAuthority record);
}