package com.banry.pscm.tenant.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;

import com.banry.pscm.tenant.persist.mapper.DynamicSourceSQLBuilder;
import com.banry.pscm.tenant.service.biz.DynamicSource;

public interface DynamicSourceMapper {
	
	@SelectProvider(type = DynamicSourceSQLBuilder.class,method = "findDSBySqlWhere")
	DynamicSource findDSBySqlWhere(String sqlWhere);
	
	@Select({"select * from dynamic_source"})
	List<DynamicSource> findDSList();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DynamicSource
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int deleteByPrimaryKey(String sourcecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DynamicSource
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int insert(DynamicSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DynamicSource
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int insertSelective(DynamicSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DynamicSource
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    DynamicSource selectByPrimaryKey(String sourcecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DynamicSource
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int updateByPrimaryKeySelective(DynamicSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DynamicSource
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int updateByPrimaryKey(DynamicSource record);
}