package com.banry.pscm.tenant.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;

import com.banry.pscm.tenant.persist.mapper.PscmBusinessSQLBuilder;
import com.banry.pscm.tenant.service.biz.PscmBusiness;

public interface PscmBusinessMapper {
	
	@SelectProvider(type = PscmBusinessSQLBuilder.class,method = "findPscmBusinessBySqlWhere")
	PscmBusiness findPscmBusinessBySqlWhere(String sqlWhere);
	
	@Select({"select * from business"})
	List<PscmBusiness> findPscmBusinessList();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int deleteByPrimaryKey(String bizcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int insert(PscmBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int insertSelective(PscmBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    PscmBusiness selectByPrimaryKey(String bizcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int updateByPrimaryKeySelective(PscmBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int updateByPrimaryKey(PscmBusiness record);
}