package com.banry.pscm.tenant.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;

import com.banry.pscm.tenant.persist.mapper.TenantRealSQLBuilder;
import com.banry.pscm.tenant.service.biz.TenantReal;
import com.banry.pscm.tenant.service.biz.TenantRealWithBLOBs;

public interface TenantRealMapper {

	@SelectProvider(type = TenantRealSQLBuilder.class,method = "findTenantRealBySqlWhere")
	List<TenantRealWithBLOBs> findTenRealBySqlWhere(String sqlWhere);
	
	@Select({ "select * from tenant_real" })
	List<TenantRealWithBLOBs> findTenantRealList();
	
	
	@Select({ "select * from tenant_real a where not exists (select 1 from tenant b where a.real_code = b.real_code)" })
	List<TenantRealWithBLOBs> findTenantRealListNotRelationTenant();

	@Insert({ "insert into tenant_real(real_code,name,address,post_code,contacter,"
			+ "telephone,real_type) "
			+ "values(#{realCode,jdbcType=VARCHAR},#{name,jdbcType=VARCHAR},#{address,jdbcType=VARCHAR},"
			+ "#{postCode,jdbcType=VARCHAR},#{contacter,jdbcType=VARCHAR},#{telephone,jdbcType=VARCHAR},"
			+ "#{realType,jdbcType=VARCHAR})" })
	int insertTenantReal(TenantReal record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tenant_real
	 *
	 * @mbg.generated Thu Apr 05 13:50:15 CST 2018
	 */
	int deleteByPrimaryKey(String realCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tenant_real
	 *
	 * @mbg.generated Thu Apr 05 13:50:15 CST 2018
	 */
	int insert(TenantRealWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tenant_real
	 *
	 * @mbg.generated Thu Apr 05 13:50:15 CST 2018
	 */
	int insertSelective(TenantRealWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tenant_real
	 *
	 * @mbg.generated Thu Apr 05 13:50:15 CST 2018
	 */
	TenantRealWithBLOBs selectByPrimaryKey(String realCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tenant_real
	 *
	 * @mbg.generated Thu Apr 05 13:50:15 CST 2018
	 */
	int updateByPrimaryKeySelective(TenantRealWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tenant_real
	 *
	 * @mbg.generated Thu Apr 05 13:50:15 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(TenantRealWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table tenant_real
	 *
	 * @mbg.generated Thu Apr 05 13:50:15 CST 2018
	 */
	int updateByPrimaryKey(TenantReal record);
}