package com.banry.pscm.tenant.persist.dao;

import java.util.List;

import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;

import com.banry.pscm.tenant.persist.mapper.TenantSQLBuilder;
import com.banry.pscm.tenant.service.biz.Tenant;

public interface TenantMapper {
	
	@SelectProvider(type = TenantSQLBuilder.class,method = "findTenantBySqlWhere")
	Tenant findTenantBySqlWhere(String sqlWhere);
	
	@SelectProvider(type = TenantSQLBuilder.class,method = "findTenantBySqlWhere")
	List<Tenant> findTenantListBySqlWhere(String sqlWhere);

	@Update("update tenant set real_code = null where tenant_code=#{tenantCode,jdbcType=VARCHAR}")
	int setRealCodeNull(String tenantCode);
	
	@Update("update tenant set source_code = null where tenant_code=#{tenantCode,jdbcType=VARCHAR}")
	int setSourceCodeNull(String tenantCode);
	
	@Select({"select * from tenant"})
	List<Tenant> findTenantList();
	
	Tenant findTenantByAccount(String account);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int deleteByPrimaryKey(String tenantcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant 
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int insert(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int insertSelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    Tenant selectByPrimaryKey(String tenantcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int updateByPrimaryKeySelective(Tenant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tenant
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    int updateByPrimaryKey(Tenant record);
}