package com.banry.pscm.tenant.service.biz;

public class BizAuthority extends BizAuthorityKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_authority.biz_chinese_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String bizChineseName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_authority.biz_chinese_name
	 * @return  the value of biz_authority.biz_chinese_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getBizChineseName() {
		return bizChineseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_authority.biz_chinese_name
	 * @param bizChineseName  the value for biz_authority.biz_chinese_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setBizChineseName(String bizChineseName) {
		this.bizChineseName = bizChineseName;
	}
}