package com.banry.pscm.tenant.service.biz;

public class BizAuthorityKey {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_authority.tenant_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String tenantCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_authority.biz_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String bizCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_authority.tenant_code
	 * @return  the value of biz_authority.tenant_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getTenantCode() {
		return tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_authority.tenant_code
	 * @param tenantCode  the value for biz_authority.tenant_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_authority.biz_code
	 * @return  the value of biz_authority.biz_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getBizCode() {
		return bizCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_authority.biz_code
	 * @param bizCode  the value for biz_authority.biz_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setBizCode(String bizCode) {
		this.bizCode = bizCode;
	}
}