package com.banry.pscm.tenant.service.biz;

public class DynamicSource {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dynamic_source.source_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String sourceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dynamic_source.source_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String sourceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dynamic_source.drive_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String driveName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dynamic_source.link_url
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String linkUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dynamic_source.user_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dynamic_source.user_password
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String userPassword;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dynamic_source.source_code
	 * @return  the value of dynamic_source.source_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getSourceCode() {
		return sourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dynamic_source.source_code
	 * @param sourceCode  the value for dynamic_source.source_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dynamic_source.source_name
	 * @return  the value of dynamic_source.source_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getSourceName() {
		return sourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dynamic_source.source_name
	 * @param sourceName  the value for dynamic_source.source_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dynamic_source.drive_name
	 * @return  the value of dynamic_source.drive_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getDriveName() {
		return driveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dynamic_source.drive_name
	 * @param driveName  the value for dynamic_source.drive_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setDriveName(String driveName) {
		this.driveName = driveName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dynamic_source.link_url
	 * @return  the value of dynamic_source.link_url
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getLinkUrl() {
		return linkUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dynamic_source.link_url
	 * @param linkUrl  the value for dynamic_source.link_url
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dynamic_source.user_name
	 * @return  the value of dynamic_source.user_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dynamic_source.user_name
	 * @param userName  the value for dynamic_source.user_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dynamic_source.user_password
	 * @return  the value of dynamic_source.user_password
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getUserPassword() {
		return userPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dynamic_source.user_password
	 * @param userPassword  the value for dynamic_source.user_password
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}
}