package com.banry.pscm.tenant.service.biz;

public class PscmBusiness {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business.biz_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String bizCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business.biz_english_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String bizEnglishName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business.biz_chinese_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String bizChineseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column business.biz_desc
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String bizDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business.biz_code
	 * @return  the value of business.biz_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getBizCode() {
		return bizCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business.biz_code
	 * @param bizCode  the value for business.biz_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setBizCode(String bizCode) {
		this.bizCode = bizCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business.biz_english_name
	 * @return  the value of business.biz_english_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getBizEnglishName() {
		return bizEnglishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business.biz_english_name
	 * @param bizEnglishName  the value for business.biz_english_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setBizEnglishName(String bizEnglishName) {
		this.bizEnglishName = bizEnglishName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business.biz_chinese_name
	 * @return  the value of business.biz_chinese_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getBizChineseName() {
		return bizChineseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business.biz_chinese_name
	 * @param bizChineseName  the value for business.biz_chinese_name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setBizChineseName(String bizChineseName) {
		this.bizChineseName = bizChineseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column business.biz_desc
	 * @return  the value of business.biz_desc
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getBizDesc() {
		return bizDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column business.biz_desc
	 * @param bizDesc  the value for business.biz_desc
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setBizDesc(String bizDesc) {
		this.bizDesc = bizDesc;
	}
}