package com.banry.pscm.tenant.service.biz;

public class TenantRealWithBLOBs extends TenantReal {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.biz_license
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private byte[] bizLicense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.other_scanner
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private byte[] otherScanner;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.biz_license
	 * @return  the value of tenant_real.biz_license
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public byte[] getBizLicense() {
		return bizLicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.biz_license
	 * @param bizLicense  the value for tenant_real.biz_license
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setBizLicense(byte[] bizLicense) {
		this.bizLicense = bizLicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.other_scanner
	 * @return  the value of tenant_real.other_scanner
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public byte[] getOtherScanner() {
		return otherScanner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.other_scanner
	 * @param otherScanner  the value for tenant_real.other_scanner
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setOtherScanner(byte[] otherScanner) {
		this.otherScanner = otherScanner;
	}
}