package com.banry.pscm.tenant.service.biz;

public class TenantReal {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.real_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String realCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.address
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.post_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.contacter
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String contacter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.telephone
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant_real.real_type
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	private String realType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.real_code
	 * @return  the value of tenant_real.real_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getRealCode() {
		return realCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.real_code
	 * @param realCode  the value for tenant_real.real_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setRealCode(String realCode) {
		this.realCode = realCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.name
	 * @return  the value of tenant_real.name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.name
	 * @param name  the value for tenant_real.name
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.address
	 * @return  the value of tenant_real.address
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.address
	 * @param address  the value for tenant_real.address
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.post_code
	 * @return  the value of tenant_real.post_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.post_code
	 * @param postCode  the value for tenant_real.post_code
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.contacter
	 * @return  the value of tenant_real.contacter
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getContacter() {
		return contacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.contacter
	 * @param contacter  the value for tenant_real.contacter
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setContacter(String contacter) {
		this.contacter = contacter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.telephone
	 * @return  the value of tenant_real.telephone
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.telephone
	 * @param telephone  the value for tenant_real.telephone
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant_real.real_type
	 * @return  the value of tenant_real.real_type
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public String getRealType() {
		return realType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant_real.real_type
	 * @param realType  the value for tenant_real.real_type
	 * @mbg.generated  Tue Jul 17 22:17:38 CST 2018
	 */
	public void setRealType(String realType) {
		this.realType = realType;
	}
}