package com.banry.pscm.tenant.service.biz;

import java.util.Date;
import java.util.List;

public class Tenant {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.tenant_code
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private String tenantCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.account
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private String account;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.password
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.name
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.tenant_type
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private Integer tenantType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.create_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.start_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.end_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.status
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tenant.parent_code
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant.RealCode
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
   // private String realcode;
    private TenantRealWithBLOBs tenantReal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tenant.SourceCode
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    //private String sourcecode;
    private DynamicSource source;
    
    
    private List<PscmBusiness> bizs;
    
    //子租户列表
    private List<Tenant> sonTenant;
    //父租户账号
    private String parentAccount;

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.tenant_code
	 * @return  the value of tenant.tenant_code
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public String getTenantCode() {
		return tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.tenant_code
	 * @param tenantCode  the value for tenant.tenant_code
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setTenantCode(String tenantCode) {
		this.tenantCode = tenantCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.account
	 * @return  the value of tenant.account
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.account
	 * @param account  the value for tenant.account
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.password
	 * @return  the value of tenant.password
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.password
	 * @param password  the value for tenant.password
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.name
	 * @return  the value of tenant.name
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.name
	 * @param name  the value for tenant.name
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.tenant_type
	 * @return  the value of tenant.tenant_type
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public Integer getTenantType() {
		return tenantType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.tenant_type
	 * @param tenantType  the value for tenant.tenant_type
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setTenantType(Integer tenantType) {
		this.tenantType = tenantType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.create_date
	 * @return  the value of tenant.create_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.create_date
	 * @param createDate  the value for tenant.create_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.start_date
	 * @return  the value of tenant.start_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.start_date
	 * @param startDate  the value for tenant.start_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.end_date
	 * @return  the value of tenant.end_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.end_date
	 * @param endDate  the value for tenant.end_date
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.status
	 * @return  the value of tenant.status
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.status
	 * @param status  the value for tenant.status
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tenant.parent_code
	 * @return  the value of tenant.parent_code
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public String getParentCode() {
		return parentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tenant.parent_code
	 * @param parentCode  the value for tenant.parent_code
	 * @mbg.generated  Tue Jul 17 15:52:39 CST 2018
	 */
	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}
	
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant.RealCode
     * 这种一对多的关系，mybatis-generator不能自动生成，需要手工修改mapper.xml文件内容
     * @author crj
     * @date 2018-04-06
     * @return the value of tenant.RealCode
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    public TenantRealWithBLOBs getTenantReal() {
        return tenantReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant.RealCode
     *
     * @param realcode the value for tenant.RealCode
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    public void setTenantReal(TenantRealWithBLOBs tenantReal) {
        this.tenantReal = tenantReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tenant.SourceCode
     *
     * @return the value of tenant.SourceCode
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    public DynamicSource getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tenant.SourceCode
     *
     * @param sourcecode the value for tenant.SourceCode
     *
     * @mbg.generated Thu Apr 05 13:50:15 CST 2018
     */
    public void setSource(DynamicSource source) {
        this.source = source;
    }
    
    /**
     * 租户与业务模块的关联是多对多的关系。这里增加一个租户拥有多个功能模块的获取
     * 这种多对多的关系，mybatis-generator不能自动生成，需要手工修改mapper.xml文件内容
     *@author crj
     *
     * @date 2018-04-06
     */
    public List<PscmBusiness> getBizs()
    {
    	return bizs;
    }
    
    /**
     * 租户与业务模块的关联是多对多的关系。这里增加一个租户拥有多个功能模块的设置
     *
     *@author crj
     * @param bizs the value list for business
     *
     * @date 2018-04-06
     */
    public void setBizs(List<PscmBusiness> bizs)
    {
    	this.bizs = bizs;
    }

	public List<Tenant> getSonTenant() {
		return sonTenant;
	}

	public void setSonTenant(List<Tenant> sonTenant) {
		this.sonTenant = sonTenant;
	}

	public String getParentAccount() {
		return parentAccount;
	}

	public void setParentAccount(String parentAccount) {
		this.parentAccount = parentAccount;
	}
    
}